stages:
  - build
  - deploy

build:
  id_tokens:
      VAULT_ID_TOKEN:
        aud: https://credentials.repository.domain.com
  tags:
      - k8s-runner
  image: image.respository.domain/image:tag
  stage: build
  script: 
    - ./obtain_credentials.sh
    - cat creds >> build.env
  artifacts:
    reports:
      dotenv: build.env
  rules:
    - changes:
      - "charts/*"
      - "charts/**/*"

deploy:
  tags:
    - k8s-runner
  image: image.respository.domain/image:tag
  stage: deploy
  dependencies:
    - build
  script: 
    - ./update_charts.sh
  rules:
    - changes:
      - "charts/*"
      - "charts/**/*"