{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}

{{- range .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .path | replace "/" "-" }}-{{ .name | replace "." "-" }}-cfmap
  namespace: {{ $namespace }}
data:
  {{ .name }}: |
{{ .data | indent 4 }}
---
{{- end }}
