{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}

{{- if and .Values.configMaps .Values.configMaps.enabled .Values.configMaps.list }}
  {{- range .Values.configMaps.list }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base_webserver.sanitizeName" (printf "%s-%s" .path .name) }}
  namespace: {{ $namespace }}
data:
  {{ .name }}: |
{{ .data | nindent 4 }}
---
  {{- end }}
{{- end }}
