{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}
{{- $ctx := dict "name" $name "Values" .Values "namespace" $namespace -}}

{{- if eq .Values.type "2" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  {{- include "base_webserver.annotations" (dict "ctx" . "annotation" .Values.annotations) | nindent 2 }}
spec:
  schedule: {{ .Values.crontab }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- include "base_webserver.annotations" (dict "ctx" . "annotation" .Values.annotationsPod) | nindent 10 }}
        spec:
          restartPolicy: OnFailure
          containers:
            {{- include "base_webserver.deploy-body" $ctx | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:

{{- include "base_webserver.deploy-body" $ctx | nindent 10 }}
{{- end }}
