{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}
{{- $ctx := dict "name" $name "Values" .Values "namespace" $namespace -}}

{{- if eq (.Values.type) "1" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $namespace }}
  name: {{ $name }}
  annotations:
    reloader.stakater.com/auto: "true"
    {{- if .Values.annotations.enabled }}
    {{- range $key, $value := .Values.annotations.list }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      {{- if .Values.annotationsPod.enabled }}  
      annotations:
        {{- range $key, $value := .Values.annotationsPod.list }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      labels:
        app: {{ $name }}
    spec:
      containers:
{{- include "base_webserver.deploy-body" $ctx | nindent 6 }}
{{- end }}
