{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}
{{- $ctx := dict "name" $name "Values" .Values "namespace" $namespace -}}

{{- if eq (.Values.type) "1" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $namespace }}
  name: {{ $name }}
  {{- include "base_webserver.annotations" (dict "ctx" . "annotation" .Values.annotations) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      {{- include "base_webserver.annotations" (dict "ctx" . "annotation" .Values.annotationsPod) | nindent 6 }}
      labels:
        app: {{ $name }}
    spec:
      containers:
{{- include "base_webserver.deploy-body" $ctx | nindent 6 }}
{{- end }}
