apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wildcard-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://<gitlab-domain>/servicios/kubernetes/gitops.git
      revision: master
      directories:
      -
      
  template:
    metadata:
      name: 'config-{{path[3]}}'
      labels: 
        env: '{{path[3]}}'
    spec:
      project: 'default'
      source:
        repoURL: https://<gitlab-domain>/servicios/kubernetes/gitops.git
        targetRevision: master
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true