apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: gitops-repo
  url: https://<gitlab-domain>/servicios/kubernetes/gitops.git
  password: "<gitlab-acces-token>"
  username: <gitlab-username> 
  insecure: "true" 
  forceHttpBasicAuth: "true" 
  enableLfs: "true"
