apiVersion: v1
kind: Secret
metadata:
  name: lab
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: lab
  server: https://<cluster-lab-direction>
  config: |
    {
      "bearerToken": "<cluster-lab-token>",
      "tlsClientConfig": {
        "insecure": false
      }
    }
