apiVersion: v1
kind: Secret
metadata:
  name: dev
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: dev
  server: https://<cluster-dev-direction>
  config: |
    {
      "bearerToken": "<cluster-dev-token>",
      "tlsClientConfig": {
        "insecure": false
      }
    }
