apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum-ui
  namespace: chartmuseum
  labels:
    app: chartmuseum-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartmuseum-ui
  template:
    metadata:
      labels:
        app: chartmuseum-ui
    spec:
      containers:
      - name: chartmuseum-ui
        image: pablogrio/chartmuseum-gui:latest
        ports:
        - name: "http"
          containerPort: 3000
        env:
        - name: PUBLIC_CHARTMUSEUM_URL
          value: http://chartmuseum:8080